browser=chrome
baseUrl=https://automationexercise.com
explicitWait=15
password=Danny1234
contactName=Danny
contactSubject=Call me back
contactMessage=Having issue with the login details
uploadFilePath=
